[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Load modules into threads

[[patches]]
[patches.module]
source = "src/libs/websocket.lua"
before = '=[SMODS twbl "threads/twitch"]'
name = "twbl/libs/websocket"
